siderolabs/bldr

Dockerfile, Makefile, cmd/pack.go, internal/pkg/constants/constants.go
This allows to use `bldr pack` without `-o` option: official `bldr`
builds will have `autonomy` as default, while for local development,
`$USERNAME` will be used instead (this includes both `bldr` image and
the images built with `bldr`). Default value can be still overridden of
course.
=> chore: default organization/registry to the ones bldr was built with

.drone.yml
There's only one image now (`-frontend`) which is used as buildkit
frontend via shebang and dockerfile.v0.
=> chore: make bldr push its images on 'master' build

internal/pkg/solver/graph.go, internal/pkg/types/v1alpha2/deps.go, internal/pkg/types/v1alpha2/pkg.go
Also adds edge de-duplication (some were duplicated when walking
dependency path multiple times).
Next PR will rework `dot` generation to avoid duplicates.
Fixes #21
=> feat: graph external dependencies (images) in addition to stages

cmd/graph.go, internal/pkg/convert/graph.go, internal/pkg/convert/node.go, internal/pkg/solver/graph.go, internal/pkg/solver/packages.go, internal/pkg/solver/set.go
This switches off dependency resolution mode and dumps all the stages
(targets) as a graph.
While working on this feature, I discovered two cases when parts of the
build graph were duplicated: first when packages were resolved, leading
to duplicate nodes in the graph, second when LLB is generated. Buildkit
seems to handle correctly LLB de-duplication, but anyway it's better to
skip duplicate entries.
Fixes #22
As examples, see talos-systems/tools#73 and talos-systems/pkgs#46
=> feat: allow 'graph' to be generated without 'target'

go.mod, go.sum, internal/pkg/convert/node.go, internal/pkg/solver/buildkit_loader.go, internal/pkg/solver/graph.go, internal/pkg/solver/packages.go, internal/pkg/types/v1alpha2/deps.go, internal/pkg/types/v1alpha2/pkg.go
Fixes #30
This adds `runtime: <bool>` flag to all the dependencies. Runtime
dependencies are implicitly in any stages using this stage (including
transitive runtime dependencies). This allows to dry up dependencies as
we list them in `pkg.yaml`.
Dependency code was rewritten while implementing this change, now
internal and external dependencies are handled in the same list.
=> feat: add support for runtime dependencies

internal/pkg/solver/buildkit_loader.go, internal/pkg/solver/filesystem_loader.go, internal/pkg/types/v1alpha2/pkg.go, internal/pkg/types/v1alpha2/pkgfile.go
And `vars:` declared in the `Pkgfile` are used to template `pkg.yaml`
files. Key `format:` is more for the future format changes, but I left
it simple until the next incompatible upgrade.
Fixes #23
=> feat: implement `Pkgfile` and support variables for templates

internal/pkg/convert/graph.go
This isn't required anymore as downloads don't happen during the build.
Also adds `--update` to `apk` calls to be on the safe side.
Fixes #31
=> chore: remove ca-certificates from base image

internal/pkg/convert/node.go, internal/pkg/pkgfile/build.go, internal/pkg/solver/buildkit_loader.go, internal/pkg/solver/filesystem_loader.go, internal/pkg/types/v1alpha2/pkg.go, internal/pkg/types/v1alpha2/source.go, internal/pkg/types/v1alpha2/steps.go, internal/pkg/types/v1alpha2/types.go
Pack of small fixes to `bldr` discovered while working on the
tests.
When loading package fails, it gets logged, but when using frontend mode
this log is hard to reach: it goes into buildkitd docker container log.
Skipped package would probably result in some dependency not being
resolvable, and actual error would be buried deep in the log.
Instead of that, abort processing and return an error which is printed
to console log when processing dockerfile frontend.
Do more validation for `pkg.yaml` as invalid field values lead to
cryptic LLB errors which are hard to match with `pkg.yaml` problems.
=> feat: stop on error in any package, more validation

README.md, cmd/validate.go, internal/pkg/solver/buildkit_loader.go, internal/pkg/solver/filesystem_loader.go
This command might be nice as a first step in CI flow to validate
structure before actually trying to build it.
This also changes loader to scan whole tree and report all the
validation errors.
=> feat: add `bldr validate` command

internal/pkg/types/v1alpha2/pkg.go
This was discovered with `tools`/`base`, as it only introduces common
runtime dependencies while not doing any build steps, so missing
`finalize` is harmless.
https://github.com/talos-systems/tools/blob/master/base/pkg.yaml
=> fix: linter shouldn't complain on `finalize` if `steps` are missing

README.md
=> docs: use correct term instead of 'shebang'

.drone.yml
This is required secret to add the builder.
=> chore: fix master build by adding `SSH_KEY`

internal/pkg/pkgfile/build.go
This causes the image manifest to be generated incorrectly.
=> fix: update properly reference to the image in export map

cmd/update.go, cmd/validate.go, internal/pkg/types/v1alpha2/source.go, internal/pkg/types/v1alpha2/source_test.go
`bldr validate --checksums`.
Refs #64.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
=> feat: add checksum validation

internal/pkg/update/github_test.go, internal/pkg/update/version.go, internal/pkg/update/version_test.go
Refs #48.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
=> fix: detect updates for runc and similar pkgs

internal/pkg/update/github.go, internal/pkg/update/github_test.go
Refs #48.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
=> fix: detect updates for containerd

README.md, internal/pkg/constants/build.go
=> feat: bump Alpine image for the `alpine` image

README.md, internal/pkg/convert/node.go, internal/pkg/environment/options.go, internal/pkg/pkgfile/build.go
In general, buildkit ignores timestamps when caching intermediate build
results, but still timestamps leak into the final container image.
So if the package is rebuilt with cache, output image stays same (even
though build step might produce different timestamps, but same content,
final output will still be cached).
This new feature enforces timestamp from `SOURCE_DATE_EPOCH` on the
output in the `finalize` step so that build is reproducible.
The downside is that if the build step is used in other steps, and
`SOURCE_DATE_EPOCH` is used, it might cause cascading rebuilds.
=> feat: implement `SOURCE_DATE_EPOCH` build argument

README.md, internal/pkg/convert/node.go, internal/pkg/types/v1alpha2/deps.go
This uses new Buildkit `Merge` operation which is exposed as
`COPY --link`. This speeds up builds a lot as eliminates some `COPY`
operations completely, and skips the `diff` stage between layers.
Also allow `--from` in `dependencies` to implement full equivalent of
`Dockerfile` `COPY` instruction.
=> feat: use new LLB merge operation, allow `from:` in deps

Makefile
Support `http_proxy` env vars.
From #88 
Signed-off-by: Niklas Wik <niklas.wik@nokia.com>
=> feat: support build behind proxy

internal/pkg/convert/node.go
Dependency resolving is complicated, bldr might skip even declared
dependencies (if they got promoted to the base image).
This fixes the check to avoid merging if only one layer will be present.
=> fix: skip merging if no dependencies found

go.mod, go.sum, internal/pkg/convert/node.go
It seems to be not needed with the recent MergeOp changes.
The promoted dependency doesn't quite work with the merged layers later
on.
Instead we can benefit from the merge layer caching.
=> fix: remove "promoted dependency" feature

internal/pkg/convert/node.go, internal/pkg/environment/options.go, internal/pkg/pkgfile/build.go
If standard `--no-cache` option is specified, `bldr` adds option to ignore cache for all `RUN` steps: all download stages are still cached, but all prepare/build/install stages are run once again.
This is very helpful for reproducibility testing.
=> feat: implement --no-cache option

internal/pkg/constants/build.go, internal/pkg/convert/graph.go, internal/pkg/convert/node.go
Use [StageX](https://stagex.tools/) instead.
Fixes #182
=> fix: drop alpine for `md5sum` step

internal/pkg/convert/node.go
This way build directory is shared between multiple steps (if any).
=> fix: use single build directory

internal/pkg/integration/testdata/sbom/final/pkg.yaml, internal/pkg/integration/testdata/sbom/final/runc.json, internal/pkg/integration/testdata/sbom/pkg/pkg.yaml, internal/pkg/sbom/sbom.go, internal/pkg/types/v1alpha2/sbom.go
This is useful to not disrupt naming schemes, but only change names in
the SBOMs.
Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>
=> feat: add `name` parameter to override names in SBOM
