.drone.yml

chore: bump docker in Drone

---

.drone.yml

chore: update channel name

---

internal/pkg/types/v1alpha1/build.go

`result` variable was accessed concurrently from two goroutines, which
might lead to unexpected behavior, including missing the actual checksum
mismatch.

chore: fix race in verify method

---

Dockerfile

chore: use Alpine 3.10 as base image for the builds

---

.drone.yml

chore: bump docker version to enable image push

---

internal/pkg/solver/graph.go

feat: add Alpine packages to the dependency graph

---

internal/pkg/convert/node.go

I missed that during the refactoring.

fix: add 'test' step to the build

---

.drone.yml

chore: fancy slack webhook message

---

Dockerfile
Makefile

Also bump Go version for the build.

chore: use git instead of gitmeta

---

internal/pkg/pkgfile/build.go

When multi-arch build is split across builders, each builder might get a
list with only a single platform, but the fact that overall build is
mulit-platform is signalled via a key. If key is set, frontend acts as
if it builds multi-platform image: export maps are generated, proper
prefixes are added to the build steps.

fix: support multi-platform key passed in via options

---

.drone.yml
Dockerfile
Makefile
README.md
cmd/frontend.go
internal/pkg/pkgfile/build.go
internal/pkg/solver/buildkit_loader.go
internal/pkg/solver/filesystem_loader.go
internal/pkg/solver/loader.go
internal/pkg/solver/packages.go
internal/pkg/types/v1alpha2/pkgfile.go

This will allow to link our packages back to the source repos.

feat: add support for image labels

---

cmd/llb.go

Useful for debugging.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

chore: add debug `--json` flag to `llb`

---

internal/pkg/convert/graph.go
internal/pkg/convert/node.go

This PR contains two optimizations:
* reorder steps to make variant + dependencies layers cacheable
* promote first dependency to base image for 'scratch' builds
First optimization is pretty simple, given that many packages contain
same top dependencies:
```yaml
dependencies:
- stage: base
```
It makes sure LLB is ordered so that base part of the LLB up to the
dependencies is identical across packages builds and can be eliminated
to a single instance.
Second optimization is more tricky, for `scratch` packages:
```yaml
variant: scratch
dependencies:
- stage: tools
- stage: libressl
```
It promotes `tools` to be base image (instead of scratch). To compare,
in `Dockerfile` syntax it means replacing:
```
FROM scratch
COPY --from=tools / /
COPY --from=libressl / /
```
with:
```
FROM tools
COPY …
```

feat: optimize build time by removing unnecessary I/O

---

internal/pkg/convert/graph.go
internal/pkg/convert/node.go
internal/pkg/environment/options.go
internal/pkg/pkgfile/build.go

This should correctly apply `HTTP_PROXY` settings when set via the build
args.

fix: respect HTTP proxy settings

---

README.md
internal/pkg/convert/node.go
internal/pkg/types/v1alpha2/steps.go

Support cache mounts
Signed-off-by: Noel Georgi <git@frezbo.dev>

feat: support cache mounts

---

Dockerfile
Makefile
README.md

Rename org
Signed-off-by: Noel Georgi <git@frezbo.dev>

chore: rename org

---

.drone.yml
.kres.yaml
Dockerfile
Makefile
hack/test/Dockerfile

Builds and pushes for arm64
Signed-off-by: Noel Georgi <git@frezbo.dev>

fix: multi arch build

---

.drone.yml

Disable running pipeline for renovate/dependabot pull requests.
Signed-off-by: Noel Georgi <git@frezbo.dev>

chore: disable drone for renovate/dependabot

---

Dockerfile
Makefile
go.mod
go.sum

chore: bump dependencies

---

.github/workflows/ci.yaml

Add a no-op GitHub workflow file.

chore: add a no-op github workflow

---

.github/workflows/ci.yaml
CHANGELOG.md
hack/release.sh
hack/release.toml

This is the official v0.2.2 release.

release(v0.2.2): prepare release

---

README.md
go.mod
go.sum
internal/pkg/convert/node.go
internal/pkg/integration/testdata/cache/check-cache/pkg.yaml
internal/pkg/integration/testdata/cache/fill-cache/pkg.yaml
internal/pkg/types/v1alpha2/steps.go

feat: support multiple cache paths

---

internal/pkg/pkgfile/build.go

Provision platforms on demand, without relying on a static list from the buildkit.

feat: provision platform context dynamically

---

internal/pkg/environment/default.go
internal/pkg/integration/testdata/variables/final/pkg.yaml
internal/pkg/integration/testdata/variables/std-vars/pkg.yaml

See https://github.com/siderolabs/toolchain/issues/129

fix: drop TOOLCHAIN from std vars

---

internal/pkg/integration/testdata/arch-amd64/final/pkg.yaml
internal/pkg/integration/testdata/arch-arm64/final/pkg.yaml
internal/pkg/integration/testdata/cache/check-cache/pkg.yaml
internal/pkg/integration/testdata/cache/fill-cache/pkg.yaml
internal/pkg/integration/testdata/platform-override/final/pkg.yaml
internal/pkg/integration/testdata/platform-override/onlyarm/pkg.yaml
internal/pkg/integration/testdata/simple/go/pkg.yaml
internal/pkg/integration/testdata/stages/final/pkg.yaml
internal/pkg/integration/testdata/stages/stage-a/pkg.yaml
internal/pkg/integration/testdata/stages/stage-b/pkg.yaml
internal/pkg/integration/testdata/stages/stage-d/stage-c/pkg.yaml
internal/pkg/integration/testdata/stages/stage-d/stage-d/pkg.yaml
internal/pkg/integration/testdata/variables/final/pkg.yaml
internal/pkg/integration/testdata/variables/global-vars/pkg.yaml
internal/pkg/integration/testdata/variables/local-vars/pkg.yaml
internal/pkg/integration/testdata/variables/override/pkg.yaml
internal/pkg/integration/testdata/variables/std-vars/pkg.yaml
internal/pkg/integration/testdata/variables/vars-yaml/inner/pkg.yaml
internal/pkg/integration/testdata/variables/vars-yaml/pkg.yaml
internal/pkg/solver/graph.go
internal/pkg/types/v1alpha2/pkg.go
internal/pkg/types/v1alpha2/variant.go

Fixes #183
Note: this is a breaking change.
Also highlight alpine variant in the graph.

feat: make variant in `pkg.yaml` explicit

---

CHANGELOG.md

This is the official v0.4.1 release.

release(v0.4.1): prepare release

---

cmd/bldr/cmd/sbom.go
internal/pkg/convert/node.go
internal/pkg/integration/testdata/sbom/final/ref.json
internal/pkg/sbom/sbom.go

This was found to be useless and create issues
Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>

fix: sbom: do not append arch

---

cmd/bldr/cmd/dump.go
internal/pkg/solver/filesystem_loader.go
internal/pkg/solver/set.go
internal/pkg/types/v1alpha2/pkg.go
internal/pkg/types/v1alpha2/templates.go

It allows to dump all packages in a set either to JSON or via Go template to be transformed into any other text.
This was used to build automatically extension catalog in https://github.com/siderolabs/extensions/pull/793

feat: implement a dump command
